### ISSUE TITLE
License key WANNA SDK

### ISSUE THREAD

**Issue by nenenkosi** [WANNABY/WannaSDK-iOS#11]
Hi 
I sent an email requesting the license key I haven’t gotten any response is there some kind of requirement to get the key? Because I thought this is an open-source product that I can try out coz it looks very interesting.

**Comment by denis-hoz** [comment]
Hello @nenenkosi,

thank you for your interest in our SDK. We would like to inform you that our SDK is designed for commercial use and is not open-source. To obtain a license key, kindly reach out to us using your business email address and furnish us with relevant information about your project. We can then proceed with fulfilling your request.
We appreciate your understanding and cooperation in this matter!
